"""Preliminary market dataset from free sources (DECISIONS D22), in the loader's format.

  G10 spot   FRED H.10 noon New York rates (17:00 London, 16:00 in a few DST weeks): one hour
             after the 16:00 London prediction-market snapshot, so a position decided at the
             snapshot of t is executed at the noon New York rate of t (conservative timing).
  EM spot    ECB euro reference rates (about 14:15 CET, crossed through USD), for BRL, MXN,
             ZAR, TRY, PLN, HUF, CZK, IDR, INR, KRW, PHP, THB, MYR. These prices come BEFORE the
             16:00 London snapshot, so Strategy B runs with a one-day execution lag on them
             (`strategy_b.exec_lag_days: 1` in the preliminary configuration).
  forward    synthetic 1-month outright from covered interest parity:
             f = s * exp(-(i_ccy - i_usd) / 12), so annualised carry = i_ccy - i_usd, with OECD
             3-month interbank rates (G10) or OECD call-money rates (EM), monthly, lagged one
             month for publication. No cross-currency basis, no NDF onshore/offshore wedge.
  bid/ask    not available: the configured fallback half-spreads are used (2 bp G10, 10 bp EM).
  yields     US 10-year Treasury (FRED DGS10, New York close).
  risk       VIX, Brent, S&P 500 price index (also used in place of MSCI World), broad dollar.
Outputs: data/raw/free_market_only/market_long.parquet and config/market_series_free.yaml.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import yaml

from src.common import ROOT, get_logger, load_config

log = get_logger("free_market")
G10_H10 = {"EUR": False, "GBP": False, "AUD": False, "NZD": False,     # True = units per USD
           "JPY": True, "CHF": True, "CAD": True, "NOK": True, "SEK": True}
EM_ECB = ["BRL", "MXN", "ZAR", "TRY", "PLN", "HUF", "CZK", "IDR", "INR", "KRW", "PHP", "THB", "MYR"]
RATE = {"USD": "r3m_US", "EUR": "r3m_EZ", "GBP": "r3m_GB", "JPY": "r3m_JP", "CHF": "r3m_CH",
        "AUD": "r3m_AU", "NZD": "r3m_NZ", "CAD": "r3m_CA", "NOK": "r3m_NO", "SEK": "r3m_SE",
        "BRL": "rcall_BR", "MXN": "rcall_MX", "ZAR": "rcall_ZA", "TRY": "rcall_TR", "PLN": "rcall_PL",
        "HUF": "rcall_HU", "CZK": "rcall_CZ", "IDR": "rcall_ID", "INR": "rcall_IN", "KRW": "rcall_KR"}


def build(start: str = "2009-06-01") -> pd.DataFrame:
    cfg = load_config()
    days = pd.bdate_range(start, cfg["sample"]["end"])
    fred = pd.read_parquet(ROOT / "data" / "raw" / "free" / "fred.parquet")
    ecb = pd.read_csv(ROOT / "data" / "raw" / "free" / "ecb_eurofxref_hist.csv", parse_dates=["Date"]).set_index("Date").sort_index()

    spot = {}
    for c, per_usd in G10_H10.items():
        s = fred[f"h10_{c}"]
        spot[c] = (1.0 / s) if per_usd else s
    for c in EM_ECB:
        if c in ecb:
            spot[c] = ecb["USD"] / ecb[c]                 # USD per unit of c
    spot = pd.DataFrame(spot).reindex(days)

    rates = {}
    for c, col in RATE.items():
        if col in fred and fred[col].notna().any():
            m = fred[col].dropna()
            m.index = m.index + pd.offsets.MonthBegin(2)   # available one month after the reference month
            rates[c] = m.reindex(m.index.union(days)).ffill().reindex(days) / 100.0
    rates = pd.DataFrame(rates)

    ccys = [c for c in spot.columns if c in rates]
    rows, mp = [], {"fx": {}, "y10": {}, "risk": {}}
    for c in ccys:
        f = spot[c] * np.exp(-(rates[c] - rates["USD"]) / 12.0)
        rows.append(pd.DataFrame({"date": days, "ticker": f"FREE_{c}", "field": "PX_LAST", "value": spot[c].values}))
        rows.append(pd.DataFrame({"date": days, "ticker": f"FREE_{c}_FWD1M", "field": "PX_LAST", "value": f.values}))
        mp["fx"][c] = {"spot": f"FREE_{c}", "fwd_outright": f"FREE_{c}_FWD1M"}
    extra = {"FREE_Y10_US": ("y10", "US", "y10_US"), "FREE_VIX": ("risk", "vix", "vix"),
             "FREE_BRENT": ("risk", "brent", "brent"), "FREE_SPX": ("risk", "spx_tr", "spx"),
             "FREE_SPX_AS_WORLD": ("risk", "msci_world_tr", "spx"), "FREE_DOLLAR": ("risk", "dxy", "dollar_broad")}
    for tk, (block, key, col) in extra.items():
        s = fred[col].reindex(days)
        rows.append(pd.DataFrame({"date": days, "ticker": tk, "field": "PX_LAST", "value": s.values}))
        mp[block][key] = {"ticker": tk}
    long = pd.concat(rows, ignore_index=True).dropna(subset=["value"])
    out = ROOT / "data" / "raw" / "free_market_only" / "market_long.parquet"
    out.parent.mkdir(parents=True, exist_ok=True)
    long.to_parquet(out, index=False)
    with open(ROOT / "config" / "market_series_free.yaml", "w", encoding="utf-8") as fh:
        fh.write("# GENERATED by src/data/free_market.py: preliminary free-data mapping (DECISIONS D22).\n")
        yaml.safe_dump(mp, fh, sort_keys=False)
    log.info("free market dataset: %d rows; currencies with price and rate: %s", len(long), ccys)
    return long


def preliminary_config() -> dict:
    """Configuration of the preliminary free-data run (D22)."""
    import copy
    cfg = copy.deepcopy(load_config())
    cfg["paths"]["raw_market"] = "data/raw/free_market_only"
    cfg["paths"]["market_series"] = "config/market_series_free.yaml"
    cfg["paths"]["results"] = "results/preliminary_free"
    cfg["strategy_b"]["exec_lag_days"] = 1
    return cfg


if __name__ == "__main__":
    build()
